/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class JFrMain extends javax.swing.JFrame {
    /**
     * Creates new form JFrMain
     */
    static boolean role;
    public JFrMain(String idNhanVien, String tenNhanVien, boolean role) {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("QUẢN LÝ CỬA HÀNG BÁNG ĐỒNG HỒ");
        setResizable(true);
        this.role = role;
        lbTenNhanVien.setText(tenNhanVien);
        lbIDNhanVien.setText(idNhanVien);
        jpnBanHang.setBackground(new Color(0, 204, 204));
        jpnSanPham.setBackground(new Color(0, 204, 204));
        jpnHoaDon.setBackground(new Color(0, 204, 204));
        jpnKhachHang.setBackground(new Color(0, 204, 204));
        jpnThoat.setBackground(new Color(0, 204, 204));
        jpnThongKe.setBackground(new Color(0, 204, 204));
        jpnSetupNV.setBackground(new Color(0, 204, 204));
        jpnNhanVien.setBackground(new Color(0, 204, 204));
        if(!role)
        {  
            lbNhanVien.setEnabled(false);
        }
//        lbNhanVien.
    }

    private JFrMain() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnMenu = new javax.swing.JPanel();
        jpnBanHang = new javax.swing.JPanel();
        lbBanHang = new javax.swing.JLabel();
        jpnSanPham = new javax.swing.JPanel();
        lbSanPham = new javax.swing.JLabel();
        jpnHoaDon = new javax.swing.JPanel();
        lbHoaDon = new javax.swing.JLabel();
        jpnKhachHang = new javax.swing.JPanel();
        lbKhachHang = new javax.swing.JLabel();
        jpnThongKe = new javax.swing.JPanel();
        lbThongKe = new javax.swing.JLabel();
        jpnSetupNV = new javax.swing.JPanel();
        lbSetupNV = new javax.swing.JLabel();
        lbTenNhanVien = new javax.swing.JLabel();
        lbIDNhanVien = new javax.swing.JLabel();
        jpnNhanVien = new javax.swing.JPanel();
        lbNhanVien = new javax.swing.JLabel();
        jpnThoat = new javax.swing.JPanel();
        lbThoat = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnMenu.setBackground(new java.awt.Color(0, 204, 204));

        lbBanHang.setBackground(new java.awt.Color(255, 255, 255));
        lbBanHang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbBanHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/banhang.png"))); // NOI18N
        lbBanHang.setText("  Bán Hàng");
        lbBanHang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbBanHangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnBanHangLayout = new javax.swing.GroupLayout(jpnBanHang);
        jpnBanHang.setLayout(jpnBanHangLayout);
        jpnBanHangLayout.setHorizontalGroup(
            jpnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnBanHangLayout.setVerticalGroup(
            jpnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbSanPham.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbSanPham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/List.png"))); // NOI18N
        lbSanPham.setText("    Sản Phẩm");
        lbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSanPhamMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnSanPhamLayout = new javax.swing.GroupLayout(jpnSanPham);
        jpnSanPham.setLayout(jpnSanPhamLayout);
        jpnSanPhamLayout.setHorizontalGroup(
            jpnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnSanPhamLayout.setVerticalGroup(
            jpnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hoadon.png"))); // NOI18N
        lbHoaDon.setText("  Hóa Đơn");
        lbHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbHoaDonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnHoaDonLayout = new javax.swing.GroupLayout(jpnHoaDon);
        jpnHoaDon.setLayout(jpnHoaDonLayout);
        jpnHoaDonLayout.setHorizontalGroup(
            jpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnHoaDonLayout.setVerticalGroup(
            jpnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbKhachHang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/khachHang.png"))); // NOI18N
        lbKhachHang.setText("  Khách Hàng");
        lbKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbKhachHangMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnKhachHangLayout = new javax.swing.GroupLayout(jpnKhachHang);
        jpnKhachHang.setLayout(jpnKhachHangLayout);
        jpnKhachHangLayout.setHorizontalGroup(
            jpnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnKhachHangLayout.setVerticalGroup(
            jpnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbThongKe.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/thongke.png"))); // NOI18N
        lbThongKe.setText("  Thống Kê");
        lbThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThongKeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnThongKeLayout = new javax.swing.GroupLayout(jpnThongKe);
        jpnThongKe.setLayout(jpnThongKeLayout);
        jpnThongKeLayout.setHorizontalGroup(
            jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnThongKeLayout.setVerticalGroup(
            jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbSetupNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/nhanvienmain.png"))); // NOI18N
        lbSetupNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSetupNVMouseClicked(evt);
            }
        });

        lbTenNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        lbTenNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTenNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbIDNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbIDNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpnSetupNVLayout = new javax.swing.GroupLayout(jpnSetupNV);
        jpnSetupNV.setLayout(jpnSetupNVLayout);
        jpnSetupNVLayout.setHorizontalGroup(
            jpnSetupNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnSetupNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnSetupNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbIDNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTenNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnSetupNVLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbSetupNV)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnSetupNVLayout.setVerticalGroup(
            jpnSetupNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSetupNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbSetupNV, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbIDNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jpnNhanVien.setForeground(new java.awt.Color(0, 204, 204));

        lbNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Person-Male-Light-icon-24.png"))); // NOI18N
        lbNhanVien.setText("   Nhân Viên");
        lbNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNhanVienMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnNhanVienLayout = new javax.swing.GroupLayout(jpnNhanVien);
        jpnNhanVien.setLayout(jpnNhanVienLayout);
        jpnNhanVienLayout.setHorizontalGroup(
            jpnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnNhanVienLayout.setVerticalGroup(
            jpnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbThoat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/thoat.png"))); // NOI18N
        lbThoat.setText("  Thoát");
        lbThoat.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lbThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnThoatLayout = new javax.swing.GroupLayout(jpnThoat);
        jpnThoat.setLayout(jpnThoatLayout);
        jpnThoatLayout.setHorizontalGroup(
            jpnThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThoatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnThoatLayout.setVerticalGroup(
            jpnThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThoatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbThoat, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnSetupNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jpnSetupNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jpnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnView.setBackground(new java.awt.Color(255, 255, 255));
        jpnView.setPreferredSize(new java.awt.Dimension(1104, 652));
        jpnView.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52))
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private JPanel childPanel;
    enum KOJpanel {
        BanHang, SanPham, NhanVien, KhachHang, ThongKe, HoaDon, NULL;
    }
    private static KOJpanel kindJpanel = KOJpanel.NULL;
    
    public void controllColor(){
        jpnBanHang.setBackground(new Color(0, 204, 204));
        jpnSanPham.setBackground(new Color(0, 204, 204));
        jpnHoaDon.setBackground(new Color(0, 204, 204));
        jpnKhachHang.setBackground(new Color(0, 204, 204));
        jpnThongKe.setBackground(new Color(0, 204, 204));
        jpnNhanVien.setBackground(new Color(0, 204, 204));
        if(kindJpanel.equals(KOJpanel.BanHang)) {
            jpnBanHang.setBackground(new Color(90, 100, 191));
        }
        if(kindJpanel.equals(KOJpanel.SanPham)) {
            jpnSanPham.setBackground(new Color(90, 100, 191));
        }
        if(kindJpanel.equals(KOJpanel.HoaDon)) {
            jpnHoaDon.setBackground(new Color(90, 100, 191));
        }
        if(kindJpanel.equals(KOJpanel.ThongKe)) {
            jpnThongKe.setBackground(new Color(90, 100, 191));
        }
        if(kindJpanel.equals(KOJpanel.KhachHang)) {
            jpnKhachHang.setBackground(new Color(90, 100, 191));
        }
        if(kindJpanel.equals(KOJpanel.NhanVien) && role) {
            jpnNhanVien.setBackground(new Color(90, 100, 191));
        }
    }
    private void lbBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbBanHangMouseClicked
        // TODO add your handling code here:
        if(kindJpanel.equals(KOJpanel.BanHang)){
            
        }
        else {
            childPanel = new jpnBanHang(lbIDNhanVien.getText());
            jpnView.removeAll();
            jpnView.add(childPanel);
            jpnView.validate();
            jpnView.updateUI();
            kindJpanel = KOJpanel.BanHang;
            controllColor();
        }
    }//GEN-LAST:event_lbBanHangMouseClicked

    private void lbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSanPhamMouseClicked
        // TODO add your handling code here:
        if(kindJpanel.equals(KOJpanel.SanPham)){
            
        }
        else {
            childPanel = new jpnSanPham();
            jpnView.removeAll();
            jpnView.add(childPanel);
            jpnView.validate();
            jpnView.updateUI();
            kindJpanel = KOJpanel.SanPham;
            controllColor();
        }
    }//GEN-LAST:event_lbSanPhamMouseClicked

    private void lbHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHoaDonMouseClicked
        // TODO add your handling code here:
        if(kindJpanel.equals(KOJpanel.HoaDon)){
            
        }
        else {
            childPanel = new jpnHoaDon();
            jpnView.removeAll();
            jpnView.add(childPanel);
            jpnView.validate();
            jpnView.updateUI();
            kindJpanel = KOJpanel.HoaDon;
            controllColor();
        }
    }//GEN-LAST:event_lbHoaDonMouseClicked

    private void lbKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbKhachHangMouseClicked
        // TODO add your handling code here:
        if(kindJpanel.equals(KOJpanel.KhachHang)){
            
        }
        else {
            childPanel = new jpnKhachHang();
            jpnView.removeAll();
            jpnView.add(childPanel);
            jpnView.validate();
            jpnView.updateUI();
            kindJpanel = KOJpanel.KhachHang;
            controllColor();
        }
    }//GEN-LAST:event_lbKhachHangMouseClicked

    private void lbThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThongKeMouseClicked
        // TODO add your handling code here:
        if(kindJpanel.equals(KOJpanel.ThongKe)){
            
        }
        else {
            childPanel = new jpnThongKe();
            jpnView.removeAll();
            jpnView.add(childPanel);
            jpnView.validate();
            jpnView.updateUI();
            kindJpanel = KOJpanel.ThongKe;
            controllColor();
        }
    }//GEN-LAST:event_lbThongKeMouseClicked

    private void lbThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThoatMouseClicked
        // TODO add your handling code here:
            JFrLogin login = new JFrLogin();
            login.setVisible(true);
            this.dispose();
            kindJpanel = KOJpanel.NULL;
            controllColor();
    }//GEN-LAST:event_lbThoatMouseClicked

    private void lbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNhanVienMouseClicked
        // TODO add your handling code here:
            if(role){ 
                if(kindJpanel.equals(KOJpanel.NhanVien)){

                }
                else {
                    childPanel = new jpnNhanVien();
                    jpnView.removeAll();
                    jpnView.add(childPanel);
                    jpnView.validate();
                    jpnView.updateUI();
                    kindJpanel = KOJpanel.NhanVien;
                    controllColor();
                }    
            }
            else{
            }

    }//GEN-LAST:event_lbNhanVienMouseClicked

    private void lbSetupNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSetupNVMouseClicked
        // TODO add your handling code here:
        JFrSetUpNV setUpNV = new JFrSetUpNV(lbIDNhanVien.getText());
        setUpNV.setDefaultCloseOperation(setUpNV.DISPOSE_ON_CLOSE);
        setUpNV.setVisible(true);
    }//GEN-LAST:event_lbSetupNVMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrMain("anhdv0", "Do Van Anh", true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpnBanHang;
    private javax.swing.JPanel jpnHoaDon;
    private javax.swing.JPanel jpnKhachHang;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnNhanVien;
    private javax.swing.JPanel jpnSanPham;
    private javax.swing.JPanel jpnSetupNV;
    private javax.swing.JPanel jpnThoat;
    private javax.swing.JPanel jpnThongKe;
    private javax.swing.JPanel jpnView;
    private javax.swing.JLabel lbBanHang;
    private javax.swing.JLabel lbHoaDon;
    private javax.swing.JLabel lbIDNhanVien;
    private javax.swing.JLabel lbKhachHang;
    private javax.swing.JLabel lbNhanVien;
    private javax.swing.JLabel lbSanPham;
    private javax.swing.JLabel lbSetupNV;
    private javax.swing.JLabel lbTenNhanVien;
    private javax.swing.JLabel lbThoat;
    private javax.swing.JLabel lbThongKe;
    // End of variables declaration//GEN-END:variables
}
