/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChiTietHoaDon;
import model.ChiTietHoaDonDAO;
import model.HoaDon;
import model.HoaDonDAO;
import model.KhachHang;
import model.KhachHangDAO;
import model.SanPham;
import model.SanPhamDAO;

/**
 *
 * @author DELL
 */
public class jpnBanHang extends javax.swing.JPanel {
    /**
     * Creates new form jpnBanHang
     */
    private static String idNhanvien;
    private List<ChiTietHoaDon> varCTHD;
    private SanPham varSP;
    private HoaDon varHoaDon;
    private ChiTietHoaDon varCTHDGioHang;
    SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
    public jpnBanHang(String idNhanVien) {
        initComponents();
        idNhanvien = idNhanVien;
        loadTbHoaDonCho();
        loadTbSanPham();
        loadDanhMuc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHoaDonCho = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbGioHang = new javax.swing.JTable();
        btnXoaCTHD = new javax.swing.JButton();
        btnXoaAllCthd = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btnCapnhat = new javax.swing.JButton();
        txtSoLuong = new javax.swing.JTextField();
        btnCong = new javax.swing.JButton();
        btTru = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTKSP = new javax.swing.JTextField();
        btnThemSanPham = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cbDanhMuc = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ChonKH = new javax.swing.JButton();
        lbIdKhachHang = new javax.swing.JLabel();
        lbTenKhachHang = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnTaoHoaDon = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnHuyHD = new javax.swing.JButton();
        lbTongTien = new javax.swing.JLabel();
        lbMaHoaDon = new javax.swing.JLabel();
        lbTienThuaTraKhach = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setPreferredSize(new java.awt.Dimension(1104, 652));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tbHoaDonCho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Nhân viên tạo", "Tên khách hàng", "Ngày tạo"
            }
        ));
        tbHoaDonCho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHoaDonChoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHoaDonCho);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("HÓA ĐƠN CHỜ");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tbGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Đơn giá", "Số lượng", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbGioHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGioHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbGioHang);

        btnXoaCTHD.setBackground(new java.awt.Color(255, 204, 204));
        btnXoaCTHD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaCTHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnXoaCTHD.setText("Xóa");
        btnXoaCTHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCTHDActionPerformed(evt);
            }
        });

        btnXoaAllCthd.setBackground(new java.awt.Color(255, 204, 204));
        btnXoaAllCthd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaAllCthd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnXoaAllCthd.setText("Xóa tất cả");
        btnXoaAllCthd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaAllCthdActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Số lượng ");

        btnCapnhat.setBackground(new java.awt.Color(255, 204, 204));
        btnCapnhat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCapnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Actions-edit-delete-icon-16.png"))); // NOI18N
        btnCapnhat.setText("Cập nhật");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });

        txtSoLuong.setText("0");
        txtSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSoLuongKeyPressed(evt);
            }
        });

        btnCong.setBackground(new java.awt.Color(255, 204, 204));
        btnCong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cong.png"))); // NOI18N
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });

        btTru.setBackground(new java.awt.Color(255, 204, 204));
        btTru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tru.png"))); // NOI18N
        btTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCong)
                            .addComponent(btTru))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCapnhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(btnXoaCTHD)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnXoaAllCthd, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnCong)
                        .addGap(18, 18, 18)
                        .addComponent(btTru))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapnhat)
                    .addComponent(btnXoaCTHD))
                .addGap(18, 18, 18)
                .addComponent(btnXoaAllCthd)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("GIỎ HÀNG");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tìm kiếm sản phẩm");

        txtTKSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTKSPKeyPressed(evt);
            }
        });

        btnThemSanPham.setBackground(new java.awt.Color(255, 204, 204));
        btnThemSanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemSanPham.setForeground(new java.awt.Color(51, 51, 51));
        btnThemSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/them24.png"))); // NOI18N
        btnThemSanPham.setText("Thêm sản phẩm");
        btnThemSanPham.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThemSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnThemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSanPhamActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Danh mục");

        cbDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDanhMucActionPerformed(evt);
            }
        });

        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Danh Mục", "Đơn giá", "Màu sắc", "Kích thước"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbSanPham);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtTKSP, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnThemSanPham))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(cbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTKSP))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("DANH SÁCH SẢN PHẨM");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Mã khách hàng:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Tên khách hàng:");

        ChonKH.setBackground(new java.awt.Color(255, 204, 204));
        ChonKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ChonKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/chon16.png"))); // NOI18N
        ChonKH.setText("Chọn");
        ChonKH.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ChonKH.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ChonKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChonKHActionPerformed(evt);
            }
        });

        lbIdKhachHang.setText("KH1");

        lbTenKhachHang.setText("Khách bán lẻ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbIdKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(ChonKH)
                        .addGap(74, 74, 74))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbIdKhachHang))
                .addGap(5, 5, 5)
                .addComponent(ChonKH, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbTenKhachHang))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Mã hóa đơn:");

        btnTaoHoaDon.setBackground(new java.awt.Color(255, 204, 204));
        btnTaoHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTaoHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tạo.png"))); // NOI18N
        btnTaoHoaDon.setText("Tạo");
        btnTaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHoaDonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Tổng tiền:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Tiền khách đưa:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Tiền thừa trả khách:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Ghi chú:");

        btnThanhToan.setBackground(new java.awt.Color(255, 204, 204));
        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThanhToan.setText("THANH TOÁN");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        jLabel14.setText("VND");

        jLabel15.setText("VND");

        jLabel16.setText("VND");

        btnHuyHD.setBackground(new java.awt.Color(255, 204, 204));
        btnHuyHD.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHuyHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/huyhd.png"))); // NOI18N
        btnHuyHD.setText("Hủy hóa đơn");
        btnHuyHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyHDActionPerformed(evt);
            }
        });

        lbTongTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTongTien.setText("0");

        lbMaHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMaHoaDon.setText("Vui lòng tạo !!   ");

        lbTienThuaTraKhach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTienThuaTraKhach.setText("0");

        txtTienKhachDua.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTienKhachDua.setText("0");
        txtTienKhachDua.setBorder(null);
        txtTienKhachDua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTienKhachDuaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField5)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lbTongTien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbTienThuaTraKhach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbMaHoaDon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addComponent(txtTienKhachDua))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16))
                                        .addGap(47, 64, Short.MAX_VALUE))
                                    .addComponent(btnTaoHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnHuyHD)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnTaoHoaDon)
                    .addComponent(lbMaHoaDon))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14)
                    .addComponent(lbTongTien))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel15)
                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel16)
                    .addComponent(lbTienThuaTraKhach))
                .addGap(26, 26, 26)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnHuyHD)
                .addGap(18, 18, 18)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("ĐƠN HÀNG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(132, 132, 132))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void loadDanhMuc(){
        SanPhamDAO loadTbSanPham = new SanPhamDAO();
        List<String> listDanhMuc = loadTbSanPham.getAllDanhMuc();
        cbDanhMuc.removeAllItems();
        cbDanhMuc.addItem(" ");
        for (String string : listDanhMuc) {
            cbDanhMuc.addItem(string);
        }
    }
    public void loadTbSanPham(){
        SanPhamDAO loadTbSanPham = new SanPhamDAO();        
        String tenSP = txtTKSP.getText();
        List<SanPham> listSanPham = new ArrayList<>();
        String danhMuc = String.valueOf(cbDanhMuc.getSelectedItem());
        if(danhMuc.isBlank()){
            if (tenSP.isBlank()){
                listSanPham = loadTbSanPham.getAllSanPham();
            }
            else {
                listSanPham = loadTbSanPham.timKiemSP(tenSP);
            }
        }
        else {
            if (tenSP.isBlank()){
                listSanPham = loadTbSanPham.timKiemSPByDanhMuc(danhMuc);
            }
            else {
                listSanPham = loadTbSanPham.timKiemSP(tenSP, danhMuc);
            }
        }
//        listSanPham = loadTbSanPham.getAllSanPham();

        DefaultTableModel modleSP = (DefaultTableModel)tbSanPham.getModel();
        modleSP.setRowCount(0);
        for (SanPham sp : listSanPham) {
            modleSP.addRow(new Object[]{sp.getIdSanPham(),
            sp.getTenSanPham(),
            sp.getTenDanhMuc(),
            sp.getGia(),
            sp.getMauSac(),
            sp.getKichThuoc()
            });
        }       
    }
    
    public void loadTbHoaDonCho(){
        HoaDonDAO loadHDCho = new HoaDonDAO();
        KhachHangDAO khDAO = new KhachHangDAO();
        List<HoaDon> listHoaDonCho = loadHDCho.getHoaDon("KT",idNhanvien);
        DefaultTableModel modleHDC = (DefaultTableModel)tbHoaDonCho.getModel();
        modleHDC.setRowCount(0);
        for (HoaDon hd : listHoaDonCho) {
            KhachHang kh = khDAO.getKhachHangByID(hd.getIdKhachHang());
            modleHDC.addRow(new Object[]{hd.getIdHoaDon(),
            hd.getIdNhanVien(),
            kh.getTenKhachHang(),
            df.format(hd.getNgayBan())
            });
        }
    }
    public void loadGioHang (){
        ChiTietHoaDonDAO loadCTHD = new ChiTietHoaDonDAO();
        SanPhamDAO spDAO = new SanPhamDAO();
        if (varHoaDon != null) {
            List<ChiTietHoaDon> listCTHD = loadCTHD.getCTHoaDonByID(varHoaDon.getIdHoaDon());
            DefaultTableModel modleCTHD = (DefaultTableModel)tbGioHang.getModel();
            modleCTHD.setRowCount(0);
            long tongTien = 0;
            for (ChiTietHoaDon cthd : listCTHD) {
                tongTien += cthd.getThanhTien();
                modleCTHD.addRow(new Object[]{cthd.getIdSanPham(),
                spDAO.getSanPhamByID(cthd.getIdSanPham()).getTenSanPham(),
                spDAO.getSanPhamByID(cthd.getIdSanPham()).getGia(),
                cthd.getSoLuong(),
                cthd.getThanhTien()
                });
            }
        lbTongTien.setText(String.valueOf(tongTien));
        }
    }
    private void tbHoaDonChoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoaDonChoMouseClicked
        // TODO add your handling code here:
        HoaDonDAO hdDAO = new HoaDonDAO();
        int row = tbHoaDonCho.getSelectedRow();
        varHoaDon = hdDAO.getHoaDonByID(Integer.parseInt(tbHoaDonCho.getValueAt(row, 0).toString()));
        lbMaHoaDon.setText(String.valueOf(varHoaDon.getIdHoaDon()));
        lbTongTien.setText(String.valueOf(varHoaDon.getTongTien()));
        lbIdKhachHang.setText(String.valueOf(varHoaDon.getIdKhachHang()));
        lbTenKhachHang.setText(tbHoaDonCho.getValueAt(row, 2).toString());
        txtTienKhachDua.setText(String.valueOf(varHoaDon.getTienKhachDua()));
        lbTienThuaTraKhach.setText(String.valueOf(varHoaDon.getTienThuaTraKhach()));
        
        loadGioHang();
        
        
    }//GEN-LAST:event_tbHoaDonChoMouseClicked

    private void btnHuyHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyHDActionPerformed
        // TODO add your handling code here:
        HoaDonDAO hdDAO = new HoaDonDAO();
        ChiTietHoaDonDAO cthdDAO = new ChiTietHoaDonDAO();
        if(tbHoaDonCho.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn hóa đơn");
        }
        else {
            cthdDAO.XoaCTHD(Integer.parseInt(lbMaHoaDon.getText()));
            hdDAO.XoaHoaDon(Integer.parseInt(lbMaHoaDon.getText()));
            loadTbHoaDonCho();
            tbHoaDonCho.setRowSelectionInterval(0, 0);
            lbMaHoaDon.setText("Vui lòng tạo !!");
        }
    }//GEN-LAST:event_btnHuyHDActionPerformed

    private void btnTaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHoaDonActionPerformed
        // TODO add your handling code here:
        HoaDonDAO hdDAO = new HoaDonDAO();
        HoaDon hd = new HoaDon();
        hd.setIdKhachHang(1);
        hd.setIdNhanVien(idNhanvien);
        hd.setNgayBan(new Date());
        hd.setTienKhachDua(0);
        hd.setTongTien(0);
        hd.setTienThuaTraKhach(0);
        hd.setTrangThai("KT");
        hdDAO.ThemHoaDon(hd);
        int row = -1 ;
        if(varHoaDon != null){
            row = tbHoaDonCho.getSelectedRow();
            loadTbHoaDonCho();
            tbHoaDonCho.setRowSelectionInterval(row, row);
        }
        else {
            loadTbHoaDonCho();
        }
    }//GEN-LAST:event_btnTaoHoaDonActionPerformed

    private void btnThemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSanPhamActionPerformed
        // TODO add your handling code here:
        ChiTietHoaDonDAO cthdDAO = new ChiTietHoaDonDAO();
        ChiTietHoaDon cthd = new ChiTietHoaDon();
        if(varHoaDon != null){
            if(varSP != null){
                cthd = cthdDAO.getCTHoaDonByID(varHoaDon.getIdHoaDon(), varSP.getIdSanPham());
                if ( cthd != null){
                    cthdDAO.updateSoLuong(cthd.getIdHoaDon(), cthd.getIdSanPham(), cthd.getSoLuong() + 1, cthd.getThanhTien() + varSP.getGia());
                }
                else {
                    cthdDAO.ThemCTHoaDon(new ChiTietHoaDon(varHoaDon.getIdHoaDon(), varSP.getIdSanPham(), 1, varSP.getGia()));
                }
                loadGioHang();
            }
            else {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn hóa đơn");
        }
    }//GEN-LAST:event_btnThemSanPhamActionPerformed

    private void tbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamMouseClicked
        // TODO add your handling code here:
        SanPhamDAO spDAO = new SanPhamDAO();
        int row = tbSanPham.getSelectedRow();
        varSP = spDAO.getSanPhamByID(Integer.parseInt(tbSanPham.getValueAt(row, 0).toString()));
        if(evt.getClickCount() >= 2){
            ChiTietHoaDonDAO cthdDAO = new ChiTietHoaDonDAO();
            ChiTietHoaDon cthd = new ChiTietHoaDon();
            if(varHoaDon != null){
                if(varSP != null){
                    cthd = cthdDAO.getCTHoaDonByID(varHoaDon.getIdHoaDon(), varSP.getIdSanPham());
                    if ( cthd != null){
                        cthdDAO.updateSoLuong(cthd.getIdHoaDon(), cthd.getIdSanPham(), cthd.getSoLuong() + 1, cthd.getThanhTien() + varSP.getGia());
                    }
                    else {
                        cthdDAO.ThemCTHoaDon(new ChiTietHoaDon(varHoaDon.getIdHoaDon(), varSP.getIdSanPham(), 1, varSP.getGia()));
                    }
                    loadGioHang();
                }
                else {
                    JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm");
                }
            }
            else {
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn hóa đơn");
            }
        }
    }//GEN-LAST:event_tbSanPhamMouseClicked

    private void tbGioHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGioHangMouseClicked
        // TODO add your handling code here:
        ChiTietHoaDonDAO cthdDAO = new ChiTietHoaDonDAO();
        int row = tbGioHang.getSelectedRow();
        int rowHD = tbHoaDonCho.getSelectedRow();  
        txtSoLuong.setText(tbGioHang.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tbGioHangMouseClicked

    private void txtSoLuongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(varHoaDon == null){
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn hóa đơn");
            }
            else{
                int row = tbGioHang.getSelectedRow();
                if(row == -1){
                    JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm trong giỏ hàng");
                }
                else {
                    int idsp = Integer.parseInt(tbGioHang.getValueAt(row, 0).toString());
                    int sl = Integer.parseInt(txtSoLuong.getText().toString());
                    int thanhTien = sl * Integer.parseInt(tbGioHang.getValueAt(row, 2).toString());
                    ChiTietHoaDonDAO cthdDAO = new ChiTietHoaDonDAO();
                    cthdDAO.updateSoLuong(varHoaDon.getIdHoaDon(), idsp  , sl, thanhTien);
                    loadGioHang();
                    tbGioHang.setRowSelectionInterval(row, row);
                }
            }
        }
    }//GEN-LAST:event_txtSoLuongKeyPressed

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
        // TODO add your handling code here:
        if(varHoaDon == null){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn hóa đơn");
        }
        else{
            int row = tbGioHang.getSelectedRow();
            if(row == -1){
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm trong giỏ hàng");
            }
            else {
                int idsp = Integer.parseInt(tbGioHang.getValueAt(row, 0).toString());
                int sl = Integer.parseInt(txtSoLuong.getText().toString());
                int thanhTien = sl * Integer.parseInt(tbGioHang.getValueAt(row, 2).toString());
                ChiTietHoaDonDAO cthdDAO = new ChiTietHoaDonDAO();
                cthdDAO.updateSoLuong(varHoaDon.getIdHoaDon(), idsp  , sl, thanhTien);
                loadGioHang();
            }
        }
    }//GEN-LAST:event_btnCapnhatActionPerformed

    private void btnXoaCTHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCTHDActionPerformed
        // TODO add your handling code here:
        ChiTietHoaDonDAO cthdDAO = new ChiTietHoaDonDAO();        
        if(varHoaDon == null){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn hóa đơn");
        }
        else{
            int row = tbGioHang.getSelectedRow();
            if(row == -1){
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm trong giỏ hàng");
            }
            else {
                int idhd = varHoaDon.getIdHoaDon();
                int idsp = Integer.parseInt(tbGioHang.getValueAt(row, 0).toString()); 
                cthdDAO.XoaCTHD(idhd, idsp);
                loadGioHang();
            }
        }
    }//GEN-LAST:event_btnXoaCTHDActionPerformed

    private void btnXoaAllCthdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaAllCthdActionPerformed
        // TODO add your handling code here:
        ChiTietHoaDonDAO cthdDAO = new ChiTietHoaDonDAO();
        if(varHoaDon == null){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn hóa đơn");
        }
        else{
            int idhd = varHoaDon.getIdHoaDon(); 
            cthdDAO.XoaCTHD(idhd);
            loadGioHang();
        }
    }//GEN-LAST:event_btnXoaAllCthdActionPerformed

    private void txtTienKhachDuaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienKhachDuaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            int tienKhachDua = Integer.parseInt(txtTienKhachDua.getText());
            int tongtien = Integer.parseInt(lbTongTien.getText());
            lbTienThuaTraKhach.setText(String.valueOf(tienKhachDua - tongtien));
        }
    }//GEN-LAST:event_txtTienKhachDuaKeyPressed

    private void txtTKSPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTKSPKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            loadTbSanPham();
        }
    }//GEN-LAST:event_txtTKSPKeyPressed

    private void cbDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDanhMucActionPerformed
        // TODO add your handling code here:
        loadTbSanPham();
    }//GEN-LAST:event_cbDanhMucActionPerformed

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        // TODO add your handling code here:
        if(varHoaDon == null){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn hóa đơn");
        }
        else{
            int row = tbGioHang.getSelectedRow();
            if(row == -1){
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm trong giỏ hàng");
            }
            else {
                int idsp = Integer.parseInt(tbGioHang.getValueAt(row, 0).toString());
                int sl = Integer.parseInt(tbGioHang.getValueAt(row, 3).toString()) + 1;
                txtSoLuong.setText(String.valueOf(sl));
                int thanhTien = sl * Integer.parseInt(tbGioHang.getValueAt(row, 2).toString());
                ChiTietHoaDonDAO cthdDAO = new ChiTietHoaDonDAO();
                cthdDAO.updateSoLuong(varHoaDon.getIdHoaDon(), idsp  , sl, thanhTien);
                loadGioHang();
                tbGioHang.setRowSelectionInterval(row, row);
            }
        }
    }//GEN-LAST:event_btnCongActionPerformed

    private void btTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTruActionPerformed
        // TODO add your handling code here:
        
        if(varHoaDon == null){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn hóa đơn");
        }
        else{
            int row = tbGioHang.getSelectedRow();
            if(row == -1){
                JOptionPane.showMessageDialog(this, "Bạn chưa chọn sản phẩm trong giỏ hàng");
            }
            else {
                int idsp = Integer.parseInt(tbGioHang.getValueAt(row, 0).toString());
                int sl = Integer.parseInt(tbGioHang.getValueAt(row, 3).toString()) - 1;
                txtSoLuong.setText(String.valueOf(sl));
                int thanhTien = sl * Integer.parseInt(tbGioHang.getValueAt(row, 2).toString());
                ChiTietHoaDonDAO cthdDAO = new ChiTietHoaDonDAO();
                cthdDAO.updateSoLuong(varHoaDon.getIdHoaDon(), idsp  , sl, thanhTien);
                loadGioHang();
                tbGioHang.setRowSelectionInterval(row, row);   
            }
        }
    }//GEN-LAST:event_btTruActionPerformed
    
    public void updateKH(KhachHang kh){
        lbIdKhachHang.setText(String.valueOf(kh.getIdKhachHang()));
        lbTenKhachHang.setText(kh.getTenKhachHang());
        int row = tbHoaDonCho.getSelectedRow();
        HoaDonDAO hdDAO = new HoaDonDAO();
        hdDAO.UpdateIdkhHoaDon(Integer.parseInt(lbMaHoaDon.getText()), kh.getIdKhachHang());
        loadTbHoaDonCho();
        tbHoaDonCho.setRowSelectionInterval(row, row);
    }
    private void ChonKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChonKHActionPerformed
        // TODO add your handling code here:
        
        if(tbHoaDonCho.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn hóa đơn");
        }
        else {
            JFrChonKH chonKH = new JFrChonKH(this);
            chonKH.setDefaultCloseOperation(chonKH.DISPOSE_ON_CLOSE);
            chonKH.setVisible(true);
        }
    }//GEN-LAST:event_ChonKHActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
         HoaDonDAO hdDAO = new HoaDonDAO();
         int tongTien = Integer.parseInt(lbTongTien.getText());
         int tienKhachDua = Integer.parseInt(txtTienKhachDua.getText());
         lbTienThuaTraKhach.setText(String.valueOf(tienKhachDua - tongTien));
         int tienTraKhach = Integer.parseInt(lbTienThuaTraKhach.getText());
         if(tienKhachDua < tongTien ){
             JOptionPane.showMessageDialog(this, "Khách chưa trả đủ tiền");
         }
         else {
            hdDAO.UpdateTTHoaDon(tongTien, tienKhachDua ,tienTraKhach, "TT", varHoaDon.getIdHoaDon() );
            varHoaDon = null;
            loadTbHoaDonCho();
         }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChonKH;
    private javax.swing.JButton btTru;
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnHuyHD;
    private javax.swing.JButton btnTaoHoaDon;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemSanPham;
    private javax.swing.JButton btnXoaAllCthd;
    private javax.swing.JButton btnXoaCTHD;
    private javax.swing.JComboBox<String> cbDanhMuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lbIdKhachHang;
    private javax.swing.JLabel lbMaHoaDon;
    private javax.swing.JLabel lbTenKhachHang;
    private javax.swing.JLabel lbTienThuaTraKhach;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JTable tbGioHang;
    private javax.swing.JTable tbHoaDonCho;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTKSP;
    private javax.swing.JTextField txtTienKhachDua;
    // End of variables declaration//GEN-END:variables
}
